import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Masonry, { ResponsiveMasonry } from 'react-responsive-masonry'
import Carousel from 'react-multi-carousel'
import 'react-multi-carousel/lib/styles.css'
//import Masonry from 'react-masonry-component'
import styles from '../styles/Home.module.css'
import NavBar from '../components/Nav'
import Layout from '../components/Layout'
import Card from '../components/Card'
import TestimonialCard from '../components/TestimonialCard'
import DestinationImg from '../components/DestinationImg'
export default function Home() {
  const responsive = {
    largeDesktop: {
      breakpoint: { max: 4000, min: 3000 },
      items: 5,
      slidesToSlide: 5
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
      slidesToSlide: 3
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
      slidesToSlide: 2
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
      slidesToSlide: 1
    }
  };
  const images = [
    {
      name: 'Amboseli',
      href: 'https://images.pexels.com/photos/1319504/pexels-photo-1319504.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    },
    {
      name: 'Zanzibar',
      href: 'https://wallpapercave.com/wp/wp4187549.jpg',
    },
    {
      name: 'Nakuru',
      href: 'https://wallpapercave.com/wp/wp4188782.jpg',
    },
    {
      name: 'Diani',
      href: 'https://images.pexels.com/photos/221471/pexels-photo-221471.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    },
    {
      name: 'Kilimanjaro',
      href: 'https://wallpapercave.com/wp/wp2254721.jpg',
    },
    {
      name: 'Ngare Ndare',
      href: 'https://wallpapercave.com/wp/wp4851359.jpg',
    },
  ];
  return (
    <div>
      <Head>
        <title>The Good Times</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <Image
              src='/images/hero.jpg'
              alt='picture of a man on a tube diving into an ocean'
              layout='fill'
              objectFit='cover'
              objectPosition='center'
              className='-z-10'
              // width={1300}
              // height={720}
          /> */}
          <div className='w-full h-screen relative -top-16 bg-hero bg-cover bg-center'>
            <div className='w-2/3 md:w-1/2 h-screen bg-black bg-opacity-50 flex items-center'>
              <div className=' border-solid border-red-500 border-2'>
                <h1 className='text-white text-2xl md:text-5xl font-bold px-4'>
                  Enjoy beautiful sights and awesome experiences
                </h1>
                <h5 className='text-white text-lg md:text-xl px-4 py-4 md:py-8 opacity-80'>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                </h5>
                <div className='w-96 border-solid border-2 border-green-500 mx-4'>
                  <ul className='flex md:justify-between'>
                    <li className='w-28 md:w-40 h-8 md:h-12 bg-blue-500 hover:bg-blue-400 rounded-lg'>
                      <Link href='/'>
                        <a className='text-white text-xs md:text-base inline-block py-1 px-2 md:px-6'>Contact Us</a>
                      </Link>
                    </li>
                    <li className='w-28 md:w-40 h-8 md:h-12 ml-6 md:ml-0 bg-white hover:bg-gray-200 rounded-lg'>
                      <Link href='/packages'>
                        <a className='text-black text-xs md:text-base inline-block py-1 px-2 md:px-6'>View Packages</a>
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div className='p-4'>
            <h1 className='text-brown text-2xl md:text-4xl text-center'>Most Popular Packages</h1>
            <div className='w-full flex flex-col md:flex-row items-center  justify-between md:px-16 py-8'>
              <Card />
              <Card /> 
              <Card />
            </div>
            
          </div>

          <div className='bg-purple-500 w-full '>
            <div className='mx-10 md:mx-20 py-10'>
              <h1 className='text-white py-5 text-2xl md:text-4xl text-center'>Our Packages Include</h1>
              <div className='flex flex-col md:flex-row items-center md:justify-between mt-6 md:mt-8'>
                <div className='flex flex-col items-center'>
                  <img src="/accomodation.svg" alt="Icon of a bed" width={160} height={160} />
                  <p className='text-white text-lg mt-4'>Accomodation</p>
                </div>
                
                <div className='flex flex-col items-center mt-7 md:mt-0'>
                  <img src="/car.svg" alt="Icon of a car" width={160} height={160} />
                  <p className='text-white text-lg mt-4'>Car Hire</p>
                </div>

                <div className='flex flex-col items-center mt-7 md:mt-0'>
                  <img src="/guide.svg" alt="Icon of a tour guide" width={160} height={160} />
                  <p className='text-white text-lg mt-4'>Tour Guide</p>
                </div>

                <div className='flex flex-col items-center mt-7 md:mt-0'>
                  <img src="/meal.svg" alt="Icon of a fork and knife" width={160} height={160} />
                  <p className='text-white text-lg mt-4'>Meals</p>
                </div>
                
              </div>
              
            </div>
          </div>

          <div className='p-8'>
            <h1 className='text-brown py-5 text-2xl md:text-4xl text-center'>Popular Destinations</h1>
            <div className='p-2 md:p-10 flex flex-col md:flex-row items-center md:justify-evenly'>
              <DestinationImg />
              <DestinationImg />
              <DestinationImg />
              <DestinationImg />
            </div>
            
            {/* <ResponsiveMasonry
              columnsCountBreakPoints={{350: 1, 750: 2, 900: 3}}
            >
              <Masonry gutter="10" >
                {
                  images.map((image, index) => (
                    <div key={index} className='bg-black h-full relative top-0'>
                        <img src={image.href} alt={image.name} />
                        
                        <h6>{image.name}</h6>
                    </div>
                    
                  ))
                }
              </Masonry>
            </ResponsiveMasonry> */}
            
          </div>

          <div className='px-5'>
            <h1 className='text-brown py-5 text-2xl md:text-4xl text-center'>What our clients say</h1>
            <div className='p-10'>
              <Carousel
                swipeable={true}
                draggable={true}
                showDots={true}
                responsive={responsive}
                ssr={true}
                infinite={true}
                // autoPlay={true}
                // autoPlaySpeed={1000}
                keyBoardControl={true}
                customTransition="all .5"
                transitionDuration={500}
                containerClass="carousel-container"
                removeArrowOnDeviceType={["tablet", "mobile"]}
                dotListClass="custom-dot-list-style"
                itemClass="carousel-item-padding-40-px"
              >
                <TestimonialCard />
                <TestimonialCard />
                <TestimonialCard />
                <TestimonialCard />
                <TestimonialCard />
                <TestimonialCard />
              </Carousel>
            </div>
          </div>

          <div className='flex flex-col md:flex-row w-full h-auto md:h-screen border-solid border-red-500 border-2 mt-9 '>
            <div className='bg-black w-full md:w-1/2 h-full flex flex-col justify-center items-center'>
              <h1 className='text-white text-2xl md:text-5xl font-semibold mt-12'>We'd love to hear from you</h1>
              <Image src='/contact-us.svg' alt='svg consisting of call, text and location icons' width={280} height={280} />
            </div>
            <div className='bg-purple-400 w-full md:w-1/2 h-full flex flex-col justify-center items-center pb-12'>
              <h1 className='text-black text-2xl md:text-4xl font-semibold mt-12 mb-5'>Contact Us</h1>

              <form className='w-2/3'>
                <div className='mb-4'>
                  <label htmlFor="name">Full Name</label>
                  <input type="text" id='name' placeholder='John Doe' className='px-6 w-full rounded-md py-2 text-gray-700 focus:outline-none' />
                </div>
                
                <div className='mb-4'>
                  <label htmlFor="email">Email</label>
                  <input type="email" id='email' placeholder='johndoe@gmail.com' className='px-6 w-full rounded-md py-2 text-gray-700 focus:outline-none' />
                </div>
                
                <div className='mb-4'>
                  <label htmlFor="phone">Phone</label>
                  <input type="text" id='phone' placeholder='0712 345 678' className='px-6 w-full rounded-md py-2 text-gray-700 focus:outline-none' />
                </div>
                
                <div className='mb-4'>
                  <label htmlFor="message">Message</label>
                  <input type="text" id='message' placeholder='Your message' className='px-6 w-full h-12 rounded-md py-2 text-gray-700 focus:outline-none' />
                </div>
                
                <button type='submit' className='w-full mt-6 py-2 rounded-md bg-blue-500 text-gray-100 hover:bg-blue-600 focus:outline-none'>Submit</button>
              </form>
            </div>
          </div>
      </Layout>
      {/* <main>
        <Image
            src='/images/hero.jpg'
            alt='picture of a man on a tube diving into an ocean'
            layout='fill'
            objectFit='cover'
            objectPosition='center'
            // width={1300}
            // height={720}
        />
        <div className='absolute z-10 w-full'>
          
        </div>
        
      </main> */}

      {/* <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span >
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
